logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
logformat = "%{time:2006-01-02T15:04:05.000} %{module}::%{shortfunc} [%{shortfile}] > %{level:.5s} - %{message}"
accesslog = "" # http access log file
addr = "localhost:8443"
#addrext = "https://mediathek.hgk.fhnw.ch/amp/"
addrext = "https://localhost:8443/"
certpem = "auto"
#certpem = "cert/server.crt" # tls client certificate file in PEM format
#keypem = "cert/server.key" # tls client key file in PEM format
linktokenexp = "1h"

[[partition]]
    name = "mediathek"
    addrext = "https://localhost:8443/mediathek"
    jwtkey = "geheim"
    jwtalg = ["HS256","HS384","HS512"]
    [partition.oai]
        signaturedomain = "mediathek.hgk.fhnw.ch"
        repositoryname = "Repository of Mediathek HGK FHNW"
        adminemail = ["tabea.lurk@fhnw.ch"]
        description = "This repository contains researchdata and OER created at Basel University of Art and Design FHNW"

[database]
    servertype = "postgres"
    dsn = "postgres://fairservice:MtgViCEqJoiQoXOP@localhost:5433/fairservice"
    connection_max = 5000
    schema = "public"

[_sshtunnel]
    user = "root"
    privatekey = "C:/daten/keys/putty_ed25519.priv.openssh"
    [sshtunnel.serverendpoint]
    port = 22
    host = "ba14ns21403.fhnw.ch"

    [[sshtunnel.tunnel]]
        name = "postgres"
        [sshtunnel.tunnel.localendpoint]
        port = 5435
        host = "localhost"

        [sshtunnel.tunnel.remoteendpoint]
        port = 5432
        host = "v000306.adm.ds.fhnw.ch"

    [[sshtunnel.tunnel]]
        name = "elasticsearch"
        [sshtunnel.tunnel.localendpoint]
        port = 5434
        host = "localhost"

        [sshtunnel.tunnel.remoteendpoint]
        port = 5432
        host = "v000306.adm.ds.fhnw.ch"
