logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
logformat = "%{time:2006-01-02T15:04:05.000} %{module}::%{shortfunc} [%{shortfile}] > %{level:.5s} - %{message}"
accesslog = "" # http access log file
addr = "localhost:8443"
#addrext = "https://mediathek.hgk.fhnw.ch/amp/"
addrext = "https://localhost:8443/"
certpem = "auto"
#certpem = "cert/server.crt" # tls client certificate file in PEM format
#keypem = "cert/server.key" # tls client key file in PEM format
jwtkey = "ov@cO+Rn,lcwmP6r:O3"
jwtalg = ["HS256", "HS384", "HS512"]
linktokenexp = "1h"

[[partition]]
    name = "mediathek"
    addrext = "https://localhost:8443/mediathek"
    jwtkey = "ov@cO+Rn,lcwmP6r:O3"
    jwtalg = ["HS256", "HS384", "HS512"]
    handleid = "20.500.11806"
    description = "This repository contains researchdata and OER created at Basel University of Art and Design FHNW"
    domain = "mediathek.hgk.fhnw.ch"
    [partition.oai]
        pagesize = 80
        resumptiontokentimeout = "3m"
        scheme = "oai"
        repositoryname = "Repository of Mediathek HGK FHNW"
        sampleIdentifier = "oai:mediathek.hgk.fhnw.ch:f1a30561-df33-11eb-8511-b0227af7e31e"
        adminemail = ["tabea.lurk@fhnw.ch"]

[datacite]
    user = "dcuser"
    password = "xxxxxxxxxxxxx"
    api = "https://api.test.datacite.org"


[database]
servertype = "postgres"
dsn = "postgres://fairservice:xxxxxxx@localhost:5433/fairservice"
connection_max = 5000
schema = "public"

[handle]
    jwtkey = "secret"
    jwtalg = "HS512"
    addr = "http://localhost:8444"

[_tunnel.ba14ns21403]
    user = "root"
    privatekey = "C:/daten/keys/putty_ed25519.priv.openssh"
    [_tunnel.ba14ns21403.endpoint]
        port = 22
        host = "ba14ns21403.fhnw.ch"
    [_tunnel.ba14ns21403.forward.postgres.local]
        port = 5433
        host = "localhost"
    [_tunnel.ba14ns21403.forward.postgres.remote]
        port = 5432
        host = "v000306.adm.ds.fhnw.ch"

